# The base URL of the site; the only required configuration variable.
base_url = "https://belloworld.it"

# The site title and description; used in feeds by default.
title = "Bello, World"
description = "Il computer è tuo, anche il software può esserlo. Informatica spiegata a chi non è del mestiere."

# The default language; used in feeds.
default_language = "it"

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

[markdown]
smart_punctuation = true

[extra]
# User settings
username = "Timothy Mario Redaelli"
email = "&#098;&#101;&#108;&#108;&#111;&#064;&#098;&#101;&#108;&#108;&#111;&#119;&#111;&#114;&#108;&#100;&#046;&#105;&#116;"
