# The URL the site will be built for
base_url = "https://belloworld.it"

title = "Bello World"
description = "Bello World Projects"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# User settings
username = "Timothy Redaelli"
user_description = ""
user_title = ""
email = "&#098;&#101;&#108;&#108;&#111;&#064;&#098;&#101;&#108;&#108;&#111;&#119;&#111;&#114;&#108;&#100;&#046;&#105;&#116;"
#twitter_username = "lorem_ipsum"
#github_username =  "lorem_ipsum"
#gplus_username =  "lorem_ipsum"

# Google-analytics
#google_analytics.id = ""
