name: Zola Deploy to Pages
on: 
  push:
    branch:
      master

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_FLAGS:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
